# Generated by Django 5.0 on 2023-12-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_format',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
    ]
