# Generated by Django 5.0 on 2023-12-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_alter_file_file_format_alter_file_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_format',
            field=models.CharField(blank=True, default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(blank=True),
        ),
    ]
